#!/bin/sh

## hyphop ##

#= build krescue rootfs

## USAGE: ./build

USAGE(){ echo "build - krescue build system

# ARGS

    -u 	opkg offline mode
    -r 	refresh opkg meta info
    -rr refresh + opkg cache

    -h|--help

"
exit 
}

. $0.lib

for p in $@; do
    case $p in
	-u)
	OPKG_NO_UPDATE=1
	;;
	-r|-rr)
	;;
	-h|--help)
	USAGE
	;;
	*)
	echo "[w] unknown param $p">&2
	exit 1
	;;
    esac

done

echo "[i] MASTER BUILD KRESCUE ">&2

## check
REQUIRED="curl"

echo "[i] check required: $REQUIRED">&2

for t in $REQUIRED ; do
    c=$(which $t) || FAIL $t not found
done

. $PR.begin

. $PR.rootfs || FAIL rootfs
. $PR.sdfs

. $PR.sdimage
. $PR.boards
. $PR.cleanup

. $PR.done
